"""Setup helpers backing the WebUI first-run flow.

These functions serve ``/api/setup/status`` and ``/api/setup/complete``
(src/web/api/config_admin.py) plus the shared ``write_env_file`` used by the
config admin (src/web/api_common.py). The interactive terminal wizard that
once lived here (``SetupWizard`` / ``run_wizard`` / a ``python -m src.setup``
CLI whose ``src/setup.py`` entry never shipped) was removed as dead code —
first-time setup is handled by the packaging installer + README steps and,
for the browser path, the WebUI setup flow these helpers implement.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

DEFAULT_CONFIG_PATH = Path("config.yml")
DEFAULT_ENV_PATH = Path(".env")
PLACEHOLDER_TOKEN = "your-discord-bot-token-here"
_DEFAULT_CONFIG: dict[str, Any] = {
    "timezone": "UTC",
    "discord": {
        "token": "${DISCORD_TOKEN}",
        "allowed_users": [],
        "channels": [],
        "respond_to_bots": False,
        "require_mention": False,
    },
    "openai_codex": {
        "enabled": True,
        "model": "gpt-5.5",
        "max_tokens": 4096,
        "credentials_path": "./data/codex_auth.json",
    },
    "context": {
        "directory": "./data/context",
        "max_system_prompt_tokens": 32000,
    },
    "sessions": {
        "max_history": 50,
        "max_age_hours": 24,
        "persist_directory": "./data/sessions",
    },
    "tools": {
        "enabled": True,
        "ssh_key_path": "~/.ssh/id_ed25519",
        "ssh_known_hosts_path": "~/.ssh/known_hosts",
        "hosts": {},
        "command_timeout_seconds": 300,
    },
    "webhook": {
        "enabled": False,
        "secret": "${WEBHOOK_SECRET:-}",
        "channel_id": "",
        "gitea_channel_id": "",
        "grafana_channel_id": "",
    },
    "learning": {
        "enabled": True,
        "max_entries": 30,
        "consolidation_target": 20,
    },
    "search": {
        "enabled": True,
        "search_db_path": "./data/search",
    },
    "logging": {
        "level": "INFO",
        "directory": "./data/logs",
    },
    "usage": {
        "directory": "./data/usage",
    },
    "browser": {
        "enabled": False,
    },
    "monitoring": {
        "enabled": False,
        "checks": [],
        "alert_channel_id": "",
        "cooldown_minutes": 60,
    },
    "permissions": {
        "tiers": {},
        "default_tier": "user",
        "overrides_path": "./data/permissions.json",
    },
    "comfyui": {
        "enabled": False,
    },
    "web": {
        "enabled": True,
        "port": 3000,
        "api_token": "",
    },
}


def validate_token_format(token: str) -> bool:
    """Check if a string looks like a valid Discord bot token.

    Discord tokens are base64-encoded and have three dot-separated parts.
    We don't validate cryptographically — just format.
    """
    if not token or not token.strip():
        return False
    parts = token.strip().split(".")
    return len(parts) == 3 and all(len(p) > 0 for p in parts)

def build_config(
    *,
    discord_token_env_ref: str = "${DISCORD_TOKEN}",
    timezone: str = "UTC",
    hosts: dict[str, dict[str, str]] | None = None,
    features: dict[str, bool] | None = None,
    web_api_token: str = "",
    claude_code_host: str = "",
) -> dict[str, Any]:
    """Build a config dict from wizard answers.

    Returns a dict ready to be written as YAML.
    """
    import copy
    cfg = copy.deepcopy(_DEFAULT_CONFIG)

    cfg["timezone"] = timezone
    cfg["discord"]["token"] = discord_token_env_ref

    if hosts:
        for name, host_info in hosts.items():
            cfg["tools"]["hosts"][name] = {
                "address": host_info["address"],
                "ssh_user": host_info.get("ssh_user", "root"),
            }

    features = features or {}
    cfg["browser"]["enabled"] = features.get("browser", False)
    cfg["comfyui"]["enabled"] = features.get("comfyui", False)

    if claude_code_host and claude_code_host in (hosts or {}):
        cfg["tools"]["claude_code_host"] = claude_code_host

    cfg["web"]["api_token"] = web_api_token

    return cfg

def build_env(discord_token: str, extra: dict[str, str] | None = None) -> str:
    """Build .env file content from wizard answers.

    Reads .env.example as a base if it exists, otherwise generates minimal content.
    """
    lines = [
        "# Odin environment configuration",
        "# Generated by setup wizard",
        "",
        f"DISCORD_TOKEN={discord_token}",
    ]
    if extra:
        lines.append("")
        for key, value in extra.items():
            lines.append(f"{key}={value}")
    lines.append("")
    return "\n".join(lines)

def is_setup_needed(
    config_path: Path = DEFAULT_CONFIG_PATH,
    env_path: Path = DEFAULT_ENV_PATH,
) -> bool:
    """Check if initial setup is needed.

    Returns True if:
    - .env doesn't exist, OR
    - DISCORD_TOKEN is the placeholder value, OR
    - config.yml doesn't exist
    """
    if not config_path.exists():
        return True
    if not env_path.exists():
        return True

    # Check if token is still the placeholder
    try:
        env_content = env_path.read_text()
        for line in env_content.splitlines():
            stripped = line.strip()
            if stripped.startswith("DISCORD_TOKEN="):
                value = stripped.split("=", 1)[1].strip()
                if value == PLACEHOLDER_TOKEN or not value:
                    return True
                return False
    except Exception:
        return True

    return True  # No DISCORD_TOKEN line found

def write_env_file(path: Path, content: str) -> None:
    """Write .env file with restricted permissions.

    Shared between the CLI wizard and the web API — single source of truth.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    try:
        path.chmod(0o600)
    except OSError:
        pass  # Windows or permission issue
